

export default function Square({ chooseSquare, val }) {
  return (
    <div onClick={chooseSquare} 
    className="h-full flex-[33%] border border-solid border-white 
    cursor-pointer grid place-items-center text-[#b9dfff] text-6xl font-sans shadow-blue-300
    hover:bg-blue-900 shadow-[0_0_2px_#fff,inset_0_0_2px_#fff,0_0_5px_#08f,0_0_15px_#08f,0_0_30px_#08f]">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
      {val}
    </div>
  )
}
